# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 14:13
from __future__ import unicode_literals

import cmdb.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='A10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('url', models.CharField(blank=True, default='https://10.2.21.', max_length=100, null=True, verbose_name='API\u7f51\u5740')),
                ('username', models.CharField(default='', help_text='\u7528\u4e8eAPI\u8fde\u63a5\u7684\u8d26\u53f7', max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, default='', help_text='\u82e5\u4e0d\u60f3\u4fee\u6539\u539f\u5bc6\u7801\uff0c\u4e0d\u7528\u8bbe\u7f6e\u6b64\u9879', max_length=50, null=True, verbose_name='\u5bc6\u7801')),
                ('ha', models.SmallIntegerField(blank=True, choices=[(1, 'DMZ\u533a'), (2, '\u6838\u5fc3\u533a'), (3, '\u5408\u4f5c\u4f19\u4f34\u533a')], default=1, null=True, verbose_name='\u9ad8\u53ef\u7528\u7ec4')),
                ('state', models.BooleanField(default=True, help_text='\u7981\u7528/\u542f\u7528', verbose_name='\u72b6\u6001')),
                ('timeout', models.IntegerField(default=5, help_text='\u8fde\u63a5HTTP API\u8d85\u65f6\u79d2\u6570', verbose_name='\u8fde\u63a5\u8d85\u65f6')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'A10\u8bbe\u5907',
                'permissions': (('admin_a10', 'A10\u7ba1\u7406\u5458'),),
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('appname', models.CharField(default='', help_text='APP\u540d\u79f0.war', max_length=100, verbose_name='APP\u540d\u79f0')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('state', models.BooleanField(default=True, help_text='\u53d6\u6d88\u52fe\u9009\u540e\u4e0d\u5728\u7f51\u7ad9\u63d0\u4f9b\u914d\u7f6e\u64cd\u4f5c', verbose_name='\u72b6\u6001')),
                ('user', models.ManyToManyField(blank=True, help_text='\u7f51\u7ad9\u54ea\u4e9b\u767b\u9646\u7528\u6237\u80fd\u5bf9\u5f53\u524dAPP\u8fdb\u884c\u64cd\u4f5c\uff0c\u8d85\u7ea7\u7528\u6237\u9ed8\u8ba4\u6709\u64cd\u4f5c\u6743\u9650', to=settings.AUTH_USER_MODEL, verbose_name='\u7f51\u7ad9\u7528\u6237')),
                ('usergroup', models.ManyToManyField(blank=True, help_text='\u7f51\u7ad9\u54ea\u4e9b\u7528\u6237\u7ec4\u80fd\u5bf9\u5f53\u524dAPP\u8fdb\u884c\u64cd\u4f5c', to='auth.Group', verbose_name='\u7f51\u7ad9\u7528\u6237\u7ec4')),
            ],
            options={
                'ordering': ['appname'],
                'verbose_name': 'APP\u9879',
            },
        ),
        migrations.CreateModel(
            name='App_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('do', models.CharField(default='', max_length=100, verbose_name='\u6267\u884c\u53c2\u6570')),
                ('path', models.CharField(blank=True, default='', max_length=60, verbose_name='\u7248\u672c\u8def\u5f84')),
                ('nod', models.CharField(blank=True, default='', max_length=60, verbose_name='\u8282\u70b9')),
                ('user', models.CharField(max_length=50, verbose_name='\u7528\u6237')),
                ('uip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7528\u6237IP')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('text', models.TextField(blank=True, default='', help_text='\u6267\u884c\u547d\u4ee4\u540e\u670d\u52a1\u5668\u8fd4\u56de\u4fe1\u606f', null=True, verbose_name='\u8fd4\u56de\u4fe1\u606f')),
            ],
            options={
                'verbose_name': 'APP\u64cd\u4f5c\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='AppConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('conf', models.CharField(default='', help_text='\u5728\u811a\u672c\u6587\u672c\u4e2d\u53ef\u76f4\u63a5\u4f7f\u7528{{\u914d\u7f6e\u9879}}\u4ee3\u8868\u5176\u5bf9\u5e94\u503c\uff0c\u9879\u540d\u79f0\u987b\u7b26\u5408\u53d8\u91cf\u547d\u540d\u89c4\u8303', max_length=100, unique=True, verbose_name='\u914d\u7f6e\u9879')),
                ('value', models.CharField(default='', help_text='\u914d\u7f6e\u6709\u4fee\u6539\uff0c\u5728100\u79d2\u5185\u751f\u6548', max_length=300, verbose_name='\u914d\u7f6e\u503c')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u4fee\u6539')),
                ('text', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['-changetime'],
                'verbose_name': 'APP\u5b8f\u89c2\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='AppConFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('confile', models.CharField(default='app.properties', help_text='\u6bd4\u5982app.properties\uff0c        \u8868\u793a\u8def\u5f84\u4e3a/data/app/tomcat/webapps/{{APP\u540d\u79f0}}/WEB-INF/classes/app.properties\uff0c\u82e5\u4e3a\u5176\u5b83\u8def\u5f84\u8bf7\u4f7f\u7528\u7edd\u5bf9\u8def\u5f84', max_length=300, verbose_name='\u914d\u7f6e\u6587\u4ef6')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u4fee\u6539')),
                ('text', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u5907\u6ce8')),
                ('app', models.ForeignKey(blank=True, help_text='\u521b\u5efa\u597d\u540e\u8bf7\u8c28\u614e\u4fee\u6539\uff01\uff01\u82e5\u4e3a\u7a7a\uff0c\u5219\u5f53\u524d\u6587\u4ef6\u914d\u7f6e\u5141\u8bb8\u4efb\u610fAPP\u8bbe\u7f6e\u4f7f\u7528\uff0c\u5426\u5219\u4e3a\u6240\u9009APP\u4e13\u7528\u914d\u7f6e', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.App', verbose_name='APP\u9879')),
            ],
            options={
                'ordering': ['confile', '-app', 'name'],
                'verbose_name': 'APP\u914d\u7f6e\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='AppConFileKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', help_text='\u914d\u7f6e\u6587\u4ef6\u4e2d\u7684\u6bcf\u884c\u8bbe\u7f6e\u9879\uff0c\u53d8\u91cf\u683c\u5f0f\u4e3a{{\u53d8\u91cf}}', max_length=300, verbose_name='\u914d\u7f6e\u9879')),
                ('value', models.CharField(blank=True, default='', help_text='\u914d\u7f6e\u6587\u4ef6\u4e2d\u7684\u6bcf\u884c\u8bbe\u7f6e\u9879\u5728\u751f\u4ea7\u73af\u5883\u4e0b\u7684\u8bbe\u7f6e\u503c\uff0c\u53d8\u91cf\u683c\u5f0f\u4e3a{{\u53d8\u91cf}}', max_length=500, verbose_name='\u914d\u7f6e\u503c')),
                ('order', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='\u6392\u5e8f')),
                ('text', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u5907\u6ce8')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('confile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.AppConFile', verbose_name='APP\u914d\u7f6e\u6587\u4ef6')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name': 'APP\u914d\u7f6e\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='AppFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u66f4\u65b0')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u8fd4\u56de\u4fe1\u606f')),
            ],
            options={
                'ordering': ['-changetime', 'cmd_id'],
                'verbose_name': 'Tomcat\u6587\u4ef6MD5',
            },
        ),
        migrations.CreateModel(
            name='AppSH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(default='.sh', help_text='\u4f7f\u811a\u672c\u80fd\u901a\u8fc7URL\u5f62\u5f0f\u6765\u8c03\u7528\uff0chttp://10.2.21.34:8088/api/sh/\u811a\u672c\u6587\u4ef6\u540d.sh', max_length=100, unique=True, verbose_name='\u811a\u672c\u6587\u4ef6\u540d')),
                ('init', models.TextField(blank=True, default='#{{app}}\nrm -rf /data/app/tomcat/temp/*\nrm -rf /data/app/tomcat/work/*\n#cd {{tomcat_path}}/webapps/{{apppath}}', help_text='\u53d8\u91cf\u683c\u5f0f\u4e3a{{\u53d8\u91cf}}\uff0c\u5907\u6ce8\u4ee5#\u5f00\u5934', null=True, verbose_name='\u811a\u672c\u521d\u59cb')),
                ('cert', models.TextField(blank=True, default='#cd {{cert_path}}', help_text='\u6bd4\u5982union_wk/RSA-qm/RSA-qm.cer\uff0c\u6bcf\u4e2a\u8bc1\u4e66\u4e00\u884c\uff0c\u53d8\u91cf\u683c\u5f0f\u4e3a{{\u53d8\u91cf}}\uff0c\u5907\u6ce8\u4ee5#\u5f00\u5934', null=True, verbose_name='\u4e0b\u8f7d\u8bc1\u4e66')),
                ('final', models.TextField(blank=True, default='\nchmod 600 WEB-INF/classes/*.properties\n', help_text='\u53d8\u91cf\u683c\u5f0f\u4e3a{{\u53d8\u91cf}}\uff0c\u5907\u6ce8\u4ee5#\u5f00\u5934', null=True, verbose_name='\u811a\u672c\u6536\u5c3e')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u4fee\u6539')),
                ('state', models.BooleanField(default=True, verbose_name='\u542f\u7528')),
                ('text', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u5907\u6ce8')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.App', verbose_name='APP\u9879')),
                ('confile', models.ManyToManyField(blank=True, help_text='\u82e5\u901a\u7528\u914d\u7f6e\u548cAPP\u4e13\u7528\u914d\u7f6e\u51b2\u7a81\uff0c\u5219\u901a\u7528\u914d\u7f6e\u4f1a\u88ab\u5ffd\u7565.<br/>', to='cmdb.AppConFile', verbose_name='\u6587\u4ef6\u914d\u7f6e')),
            ],
            options={
                'ordering': ['app__appname', 'file'],
                'verbose_name': 'APP\u914d\u7f6e\u811a\u672c',
                'permissions': (('run_appsh', 'Can run_appsh'),),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('vip', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='VIP')),
                ('vport', models.CharField(blank=True, default='', help_text='\u5982\u679c\u6709\u591a\u4e2a\u7aef\u53e3\u4f7f\u7528\u9017\u53f7\u95f4\u9694\uff0c\u6bd4\u59828080,28000', max_length=200, null=True, verbose_name='VIP\u7aef\u53e3')),
                ('ptype', models.SmallIntegerField(choices=[(1, 'HTTP'), (2, 'TCP')], default=1, verbose_name='\u7aef\u53e3\u7c7b\u578b')),
                ('port', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u540e\u7aef\u7aef\u53e3')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('info', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u5176\u5b83\u4fe1\u606f')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('a10', models.ManyToManyField(blank=True, to='cmdb.A10', verbose_name='A10\u8bbe\u5907')),
            ],
            options={
                'verbose_name': '\u8d1f\u8f7d\u5747\u8861',
            },
        ),
        migrations.CreateModel(
            name='Balance2Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u540e\u7aef\u7aef\u53e3')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Balance', verbose_name='\u8d1f\u8f7d\u5747\u8861')),
            ],
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u8bc1\u4e66\u540d\u79f0')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, '\u5728\u7528'), (2, '\u672a\u7528'), (3, '\u4e0b\u7ebf')], default=1, null=True, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('state', models.SmallIntegerField(blank=True, choices=[(1, '\u6b63\u5e38'), (2, '\u5c06\u8fc7\u671f'), (3, '\u5df2\u8fc7\u671f')], editable=False, null=True, verbose_name='\u8fc7\u671f\u72b6\u6001')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('ctype', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u7528\u9014/\u7c7b\u578b')),
                ('geshi', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='\u8bc1\u4e66\u683c\u5f0f')),
                ('users', models.TextField(blank=True, default='', null=True, verbose_name='\u4f7f\u7528\u8005')),
                ('apps', models.TextField(blank=True, default='', null=True, verbose_name='\u5e94\u7528\u5217\u8868')),
                ('exp_date', models.DateTimeField(verbose_name='\u5230\u671f\u65f6\u95f4')),
                ('days', models.IntegerField(default=60, help_text='\u5728\u5230\u671f\u65f6\u95f4\u4e4b\u524d\uff0c\u63d0\u524d\u591a\u5c11\u5929\u8fdb\u884c\u901a\u77e5', verbose_name='\u63d0\u524d\u901a\u77e5')),
                ('send', models.BooleanField(default=False, verbose_name='\u5df2\u901a\u77e5')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='\u901a\u77e5\u65f6\u95f4')),
                ('path', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u76ee\u5f55')),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5bc6\u7801')),
                ('sn', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('sf', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u7b7e\u540d\u7b97\u6cd5')),
                ('hx', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u54c8\u5e0c\u7b97\u6cd5')),
                ('users2', models.TextField(blank=True, default='', null=True, verbose_name='\u9882\u53d1\u8005')),
                ('rsa', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u516c\u94a5')),
                ('send_user', models.ManyToManyField(help_text='\u6240\u9009\u7528\u6237\u5c06\u6536\u5230\u90ae\u4ef6/\u5fae\u4fe1--\u8bc1\u4e66\u8fc7\u671f\u901a\u77e5', to=settings.AUTH_USER_MODEL, verbose_name='\u901a\u77e5\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8bc1\u4e66',
            },
        ),
        migrations.CreateModel(
            name='CMD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField(verbose_name='\u547d\u4ee4\u5185\u5bb9')),
                ('ctype', models.SmallIntegerField(blank=True, choices=[(1, 'GREP\u65e5\u5fd7'), (2, '\u5e38\u7528\u811a\u672c'), (4, 'APP\u914d\u7f6e\u8f83\u9a8c'), (6, '\u81ea\u5b9a\u4e49\u547d\u4ee4')], default=1, null=True, verbose_name='\u547d\u4ee4\u7c7b\u578b')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('end', models.BooleanField(default=False, verbose_name='\u4efb\u52a1\u5b8c\u6210')),
            ],
            options={
                'verbose_name': 'CMD\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='CMD_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u8fd4\u56de\u4fe1\u606f')),
                ('cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.CMD', verbose_name='\u547d\u4ee4')),
            ],
            options={
                'verbose_name': 'CMD\u7ed3\u679c',
            },
        ),
        migrations.CreateModel(
            name='DockerCompose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('scale', models.CharField(blank=True, default='', help_text='scale\u53c2\u6570\uff0c\u9ed8\u8ba4\u6bcf\u4e2a\u670d\u52a1\u53ea\u542f\u52a81\u4e2a\u5bb9\u5668\uff0c\u591a\u4e2a\u65f6\u6bd4\u5982\u8bbe\u7f6eweb=2,worker=3                             <br/>\u9700\u542f\u52a8\u591a\u4e2a\u5bb9\u5668\u7684\u670d\u52a1\uff0c\u4e0d\u80fd\u914d\u7f6eIP\u3001\u5bb9\u5668\u540d\u7b49\u552f\u4e00\u9879\uff0c\u4ee5\u514d\u51b2\u7a81', max_length=100, verbose_name='\u6570\u91cf\u53c2\u6570')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('text', models.CharField(blank=True, default='', max_length=300, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5bb9\u5668\u7f16\u6392',
            },
        ),
        migrations.CreateModel(
            name='DockerHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='\u5bbf\u4e3b\u673aIP')),
                ('port', models.IntegerField(default=2375, verbose_name='Docker\u7aef\u53e3')),
                ('tls', models.BooleanField(default=True, help_text='Docker-API\u4e0d\u4f1a\u8fdb\u884c\u5b89\u5168\u9a8c\u8bc1\uff0c\u4efb\u610f\u63a5\u5165\u7684\u5ba2\u6237\u7aef\u90fd\u80fd\u8fdb\u884c\u6240\u6709\u64cd\u4f5c<br/>\u4e3a\u5b89\u5168\u9700\u914d\u7f6eTLS\uff0c\u5ba2\u6237\u7aef\u4f7f\u7528\u8bc1\u4e66\u8bbf\u95eeAPI\u63a5\u53e3', verbose_name='TLS')),
                ('text', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u5bb9\u5668\u5bbf\u4e3b\u673a',
                'permissions': (('images_manage', '\u955c\u50cf\u7ba1\u7406'), ('containers_manage', '\u5bb9\u5668\u7ba1\u7406'), ('net_manage', '\u5bb9\u5668\u7ba1\u7406')),
            },
        ),
        migrations.CreateModel(
            name='DockerImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u955c\u50cf\u540d')),
                ('ver', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7248\u672c')),
                ('file', models.CharField(max_length=100, unique=True, verbose_name='\u6587\u4ef6\u540d')),
                ('size', models.BigIntegerField(default=0, verbose_name='\u6587\u4ef6\u5927\u5c0f')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('upload', models.BooleanField(default=False, verbose_name='\u624b\u5de5\u4e0a\u4f20')),
                ('text', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('dockerhost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.DockerHost', verbose_name='\u6765\u6e90/\u5bbf\u4e3b\u673a')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5bb9\u5668\u955c\u50cf\u5305',
            },
        ),
        migrations.CreateModel(
            name='DockerYml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('file', models.CharField(max_length=100, verbose_name='yml\u6587\u4ef6\u540d')),
                ('text', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('state', models.BooleanField(default=True, verbose_name='\u542f\u7528')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5bb9\u5668YML',
            },
        ),
        migrations.CreateModel(
            name='DockerYmlGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7c7b\u540d')),
                ('path', models.CharField(max_length=100, unique=True, verbose_name='yml\u76ee\u5f55')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5bb9\u5668YML\u5206\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='ES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('port', models.IntegerField(default=9200, verbose_name='ES\u7aef\u53e3')),
                ('cluster', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u96c6\u7fa4\u540d\u79f0')),
                ('node', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u8282\u70b9\u540d\u79f0')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'ordering': ['host'],
                'verbose_name': 'ES\u8282\u70b9',
            },
        ),
        migrations.CreateModel(
            name='Fault_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('ftype', models.CharField(choices=[('\u7f51\u7edc', '\u7f51\u7edc'), ('\u670d\u52a1\u5546', '\u670d\u52a1\u5546'), ('\u6570\u636e\u5e93', '\u6570\u636e\u5e93'), ('\u7cfb\u7edf\u670d\u52a1\u5668', '\u7cfb\u7edf\u670d\u52a1\u5668'), ('\u5e94\u7528', '\u5e94\u7528'), ('\u5176\u5b83', '\u5176\u5b83')], max_length=50, verbose_name='\u6545\u969c\u7c7b\u578b')),
                ('ftime', models.DateTimeField(verbose_name='\u6545\u969c\u65f6\u95f4')),
                ('oktime', models.DateTimeField(blank=True, null=True, verbose_name='\u6062\u590d\u65f6\u95f4')),
                ('plan', models.BooleanField(default=False, verbose_name='\u8ba1\u5212\u5185')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u6545\u969c\u8be6\u60c5')),
                ('res', models.TextField(blank=True, default='', null=True, verbose_name='\u9020\u6210\u5f71\u54cd')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8fd0\u7ef4\u6545\u969c\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='\u7528\u4e8e\u4eba\u5de5\u8fa8\u522b\uff0c\u81ea\u52a8\u811a\u672c\u9ed8\u8ba4\u8bbe\u7f6e\u4e3a\u4e3b\u673a\u540d\uff0c\u53ef\u6539\u4e3a\u5176\u5b83\u4fbf\u4e8e\u4eba\u5458\u8bc6\u522b\u7684\u540d\u79f0', max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('hostname', models.CharField(help_text='\u5173\u952e\u5b57\u6bb5\uff0c\u8bf7\u8c28\u614e\u4fee\u6539', max_length=50, unique=True, verbose_name='\u4e3b\u673a\u540d/\u8ba1\u7b97\u673a\u540d')),
                ('ip', models.GenericIPAddressField(help_text='\u82e5\u6709\u591a\u4e2aIP\u4e14\u4e3b\u673a\u540d\u65e0\u6307\u5b9a\u89e3\u6790\u5219\u9ed8\u8ba4\u4e3a0.0.0.0\uff0c\u8bf7\u5728\u5ba2\u6237\u7aef/etc/hosts\u4e2d\u8bbe\u7f6e\u5176\u4e3b\u673a\u540d\u5bf9\u5e94IP\u89e3\u6790', verbose_name='\u7ba1\u7406IP')),
                ('port', models.IntegerField(blank=True, default=22, null=True, verbose_name='ssh\u7aef\u53e3')),
                ('other_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5176\u5b83IP')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, '\u5728\u7528'), (2, '\u5907\u7528'), (3, '\u6545\u969c'), (4, '\u4e0b\u7ebf'), (6, '\u5176\u5b83')], default=1, null=True, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('asset_type', models.SmallIntegerField(blank=True, choices=[(1, '\u7269\u7406\u673a'), (2, '\u865a\u62df\u673a'), (3, '\u5bb9\u5668'), (4, 'H3C\u4ea4\u6362\u673a'), (6, '\u5176\u5b83')], default=1, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('os', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu_model', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='CPU\u578b\u53f7')),
                ('cpu_num', models.CharField(blank=True, default='', help_text='\u7269\u7406\u6838\u4e2a\u6570, \u903b\u8f91\u6838\u4e2a\u6570\uff0c(intel\u9ad8\u7aefCPU\u5e26\u8d85\u7ebf\u7a0b\u6280\u672f)', max_length=100, null=True, verbose_name='CPU\u6570\u91cf')),
                ('memory', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('disk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u786c\u76d8\u4fe1\u606f')),
                ('vendor', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='\u4f9b\u5e94\u5546')),
                ('sn', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='\u4e3b\u673a\u5e8f\u5217\u53f7')),
                ('ports', models.TextField(blank=True, default='', help_text='\u4e3b\u673a\u4e0a\u5904\u4e8e\u76d1\u542c\u72b6\u6001\u7684TCP\u548cUDP\u7aef\u53e3', null=True, verbose_name='\u76d1\u542c\u7aef\u53e3')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('agenttime', models.DateTimeField(blank=True, help_text='\u6700\u8fd1\u4e00\u6b21\u4e3b\u673a\u5ba2\u6237\u7aef\u81ea\u52a8\u811a\u672c\u8fd0\u884c\u66f4\u65b0\u8f6f\u786c\u4ef6\u4fe1\u606f\u7684\u65f6\u95f4', null=True, verbose_name='\u914d\u7f6e\u66f4\u65b0')),
                ('buydate', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('position', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='\u6240\u5904\u4f4d\u7f6e')),
                ('sernumb', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='\u670d\u52a1\u7f16\u53f7')),
                ('sercode', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='\u670d\u52a1\u4ee3\u7801')),
                ('tomcat', models.CharField(default='/data/app/tomcat', max_length=100, verbose_name='Tomcat\u76ee\u5f55')),
                ('tomcat_ver', models.CharField(blank=True, default='', max_length=50, verbose_name='Tomcat\u7248\u672c')),
                ('jdk_ver', models.CharField(blank=True, default='', max_length=50, verbose_name='JDK\u7248\u672c')),
                ('kernel', models.CharField(blank=True, default='', max_length=60, verbose_name='\u7cfb\u7edf\u5185\u6838\u7248\u672c')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('admin', models.ForeignKey(blank=True, help_text='\u8d1f\u8d23\u4eba\u76f4\u63a5\u6709(\u5f53\u524d\u4e3b\u673a/\u540d\u4e0b\u4e3b\u673a)\u64cd\u4f5c\u6743\u9650', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set2', to=settings.AUTH_USER_MODEL, verbose_name='\u7ba1\u7406\u4eba')),
                ('app', models.ManyToManyField(blank=True, help_text='\u5f53\u524d\u4e3b\u673a\u5305\u542b\u7684APP\uff0c\u5728APP\u914d\u7f6e\u9875\u9009\u62e9\u4e3b\u673a\u540e\uff0c\u663e\u793a\u4e3b\u673a\u540d\u4e0b\u7684APP\u6e05\u5355', to='cmdb.App', verbose_name='APP\u9879\u76ee')),
            ],
            options={
                'ordering': ['group', 'ip'],
                'verbose_name': '\u4e3b\u673a',
                'permissions': (('deploy_host', 'Can deploy host'), ('ssh_host', 'Can ssh host'), ('sftp_host', 'Can sftp host'), ('grep_host', 'Can grep host'), ('run_sh_host', 'Can run_sh host'), ('run_cmd_host', 'Can run_cmd host'), ('other_do_host', 'Can other_do host')),
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d/\u533a\u57df')),
                ('ip', models.CharField(blank=True, default='', help_text='IP\u5f00\u5934\u5b57\u7b26\uff0c\u6bd4\u5982Core\u7ec4IP\u4e3a10.2.4.\u5f00\u5934\u3002\u7528\u4e8e\u5ba2\u6237\u7aef\u811a\u672c\u6dfb\u52a0\u65b0\u4e3b\u673a\u65f6\u81ea\u52a8\u8bbe\u7f6e\u7ec4\uff0c\u4e0d\u652f\u6301\u901a\u914d\u7b26', max_length=20, verbose_name='IP\u5339\u914d')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u4e3b\u673a\u5206\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Mail_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u540d\u79f0')),
                ('mails', models.CharField(default='', max_length=100, verbose_name='\u6536\u4ef6\u4eba')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ok', models.BooleanField(default=True, verbose_name='\u6210\u529f\u53d1\u9001')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u8be6\u7ec6\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u90ae\u4ef6\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=10, verbose_name='\u8282\u70b9')),
                ('txt', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.App', verbose_name='APP')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'ordering': ['app', 'host', 'node'],
                'verbose_name': 'APP\u90e8\u7f72\u8282\u70b9',
            },
        ),
        migrations.CreateModel(
            name='OSS_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, verbose_name='\u6587\u4ef6/\u8def\u5f84')),
                ('dotype', models.SmallIntegerField(choices=[(0, '\u5220\u9664'), (1, '\u4e0a\u4f20'), (2, '\u91cd\u547d\u540d')], verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('dotime', models.DateTimeField(auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('http', models.CharField(blank=True, help_text='\u963f\u91cc\u4e91OSS\u8fd4\u56de\u7684HTTP\u72b6\u6001\u7801', max_length=300, null=True, verbose_name='\u72b6\u6001\u7801')),
                ('request_id', models.CharField(blank=True, help_text='\u672c\u6b21\u8fde\u63a5\u963f\u91cc\u4e91OSS\u7684\u8bf7\u6c42ID\uff0c\u552f\u4e00\u6807\u8bc6', max_length=300, null=True, verbose_name='\u8bf7\u6c42ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u963f\u91cc\u4e91OSS\u6587\u4ef6\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='SH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u6807\u8bc6\u540d')),
                ('fname', models.CharField(default='', help_text='\u4f7f\u811a\u672c\u80fd\u901a\u8fc7URL\u5f62\u5f0f\u6765\u8c03\u7528\uff0chttp://10.2.21.34:8088/api/sh/\u6587\u4ef6\u540d\uff0c\u5e76\u4e14\u901a\u8fc7\u540e\u7f00\u540d\u533a\u5206py\u3001sh\u811a\u672c', max_length=100, verbose_name='\u6587\u4ef6\u540d')),
                ('sh', models.SmallIntegerField(blank=True, choices=[(1, '\u9ed8\u8ba4'), (2, 'H3C\u4ea4\u6362\u673a'), (3, 'APP\u914d\u7f6e')], default=1, null=True, verbose_name='\u811a\u672c\u7c7b\u578b')),
                ('cmd', models.TextField(blank=True, null=True, verbose_name='\u811a\u672c\u5185\u5bb9')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['sh', 'fname'],
                'verbose_name': '\u5e38\u7528\u547d\u4ee4/\u811a\u672c',
            },
        ),
        migrations.CreateModel(
            name='SSH_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='', editable=False, max_length=100, verbose_name='channel')),
                ('log', models.CharField(default=cmdb.models.get_logname, editable=False, max_length=100, unique=True, verbose_name='\u6587\u4ef6\u540d')),
                ('cmds', models.TextField(blank=True, help_text='\u7528\u6237\u7ec8\u7aef\u64cd\u4f5c\u6240\u6267\u884c\u7684\u547d\u4ee4\u8bb0\u5f55', null=True, verbose_name='\u547d\u4ee4\u8bb0\u5f55')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-start_time'],
                'verbose_name': '\u7ec8\u7aef\u64cd\u4f5c\u8bb0\u5f55',
                'permissions': (('replay_ssh_log', '\u64ad\u653e\u7ec8\u7aef\u64cd\u4f5c'),),
            },
        ),
        migrations.CreateModel(
            name='SshUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='\u6807\u8bc6\u540d\u79f0\uff0c\u5f53\u4e0d\u540c\u670d\u52a1\u5668\u4f7f\u7528\u76f8\u540c\u7684SSH\u8d26\u53f7\u540d\uff0c\u4f46\u5bc6\u7801\u4e0d\u540c\u65f6\uff0c\u6b64\u9879\u540d\u79f0\u53ef\u8fdb\u884c\u533a\u5206\u3002', max_length=50, verbose_name='\u540d\u79f0')),
                ('username', models.CharField(default='', max_length=50, verbose_name='SSH\u8d26\u53f7')),
                ('password', models.CharField(blank=True, default='', help_text='\u82e5\u4e0d\u60f3\u4fee\u6539\u539f\u5bc6\u7801\uff0c\u4e0d\u7528\u8bbe\u7f6e\u6b64\u9879', max_length=50, null=True, verbose_name='\u5bc6\u7801')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u4fee\u6539')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u4e3b\u673aSSH\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='SshUserCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, verbose_name='\u4f7f\u7528\u5bc6\u7801')),
                ('error', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='\u5931\u8d25\u539f\u56e0')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'ordering': ['host__ip'],
                'verbose_name': '\u4e3b\u673aSSH\u5bc6\u7801\u5931\u8d25\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='Tomcat_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='\u4e3b\u673aIP')),
                ('appname', models.CharField(default='', max_length=100, verbose_name='APP\u540d\u79f0')),
                ('node', models.SmallIntegerField(blank=True, null=True, verbose_name='\u8282\u70b9')),
                ('dotype', models.SmallIntegerField(choices=[(0, '\u505c\u6b62'), (1, '\u542f\u52a8')], verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'Tomcat\u542f\u52a8\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftp_readonly', models.BooleanField(default=False, help_text='SFTP\u6587\u4ef6\u7ba1\u7406\u65f6\u53ea\u8bfb', verbose_name='SFTP\u53ea\u8bfb')),
                ('weixin', models.CharField(blank=True, default='', help_text='\u9700\u8981\u65f6\uff0c\u7528\u4e8e\u63a5\u6536\u7531\u516c\u53f8\u516c\u4f17\u53f7\u53d1\u7ed9\u5f53\u524d\u7528\u6237\u7684\u5fae\u4fe1\u544a\u8b66\u4fe1\u606f', max_length=100, null=True, verbose_name='\u5fae\u4fe1ID')),
                ('otp', models.BooleanField(default=True, help_text='\u5f53\u524d\u7528\u6237\u767b\u9646\u65f6\uff0c\u662f\u5426\u9700\u8fdb\u884cT-otp\u9a8c\u8bc1', verbose_name='OTP\u9a8c\u8bc1')),
                ('show_otp', models.BooleanField(default=True, help_text='\u65b0\u7528\u6237\u9996\u6b21\u767b\u9646\uff0c\u6216\u8005\u624b\u673a\u4e22\u5931\u4e86otp\u4fe1\u606f\uff0c\u9700\u91cd\u65b0\u626b\u7801\u7528\u4e8e\u751f\u6210otp\u9a8c\u8bc1\uff0c\u9a8c\u8bc1\u6210\u529f\u540e\u4e0d\u518d\u63d0\u4f9b\u663e\u793a', verbose_name='\u663e\u793aotp\u4e8c\u7ef4\u7801')),
                ('yx', models.SmallIntegerField(default=365, help_text='\u7528\u6237\u6709\u6548\u671f\u5929\u6570\uff0c\u8fc7\u671f\u540e\u81ea\u52a8\u505c\u7528', verbose_name='\u6709\u6548\u671f')),
                ('usertime', models.DateTimeField(default=datetime.datetime.now, help_text='\u7528\u4e8e\u8ba1\u7b97/\u4fdd\u5b58\u7528\u6237\u8fc7\u671f\u65e5\u671f', verbose_name='\u4e0a\u6b21\u8fc7\u671f')),
                ('pwdtime', models.DateTimeField(default=datetime.datetime.now, help_text='\u7528\u4e8e\u8ba1\u7b97\u5bc6\u7801\u8fc7\u671f\u65e5\u671f', verbose_name='\u4e0a\u6b21\u4fee\u6539\u5bc6\u7801')),
                ('expired', models.SmallIntegerField(default=90, help_text='\u5bc6\u7801\u8fc7\u671f\u5929\u6570\uff0c\u8fc7\u671f\u540e\u767b\u9646\u9700\u4fee\u6539\u5bc6\u7801', verbose_name='\u5bc6\u7801\u8fc7\u671f')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6269\u5c55\u4fe1\u606f',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sshuser',
            unique_together=set([('name', 'username')]),
        ),
        migrations.AlterUniqueTogether(
            name='sh',
            unique_together=set([('sh', 'fname')]),
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.HostGroup', verbose_name='\u7ec4/\u5b89\u5168\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='host',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='\u8bbe\u5907\u7c7b\u578b\u4e3a\u865a\u62df\u673a/\u5bb9\u5668\u65f6\uff0c\u8bbe\u7f6e\u6240\u5728\u7269\u7406\u673a', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Host', verbose_name='\u6240\u5c5e\u7269\u7406\u673a'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_user',
            field=models.ForeignKey(blank=True, help_text='\u5f53\u524d\u4e3b\u673a\u7684SSH\u7528\u6237\uff0c\u7528\u4e8essh\u8fde\u63a5\u6267\u884c\u547d\u4ee4\u6216\u7ec8\u7aefWEB SSH', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.SshUser', verbose_name='SSH\u7ec8\u7aef\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.ManyToManyField(blank=True, help_text='\u7f51\u7ad9\u54ea\u4e9b\u7528\u6237\u80fd\u5bf9\u5f53\u524d\u4e3b\u673a\u8fdb\u884c\u64cd\u4f5c\uff0c\u8d85\u7ea7\u7528\u6237\u76f4\u63a5\u6709\u64cd\u4f5c\u6743\u9650', to=settings.AUTH_USER_MODEL, verbose_name='\u7f51\u7ad9\u7528\u6237\u6743\u9650'),
        ),
        migrations.AddField(
            model_name='host',
            name='usergroup',
            field=models.ManyToManyField(blank=True, help_text='\u7f51\u7ad9\u54ea\u4e9b\u7528\u6237\u7ec4\u80fd\u5bf9\u5f53\u524d\u4e3b\u673a\u8fdb\u884c\u64cd\u4f5c', to='auth.Group', verbose_name='\u7f51\u7ad9\u7528\u6237\u7ec4'),
        ),
        migrations.AddField(
            model_name='es',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u6240\u5728\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='dockeryml',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.DockerYmlGroup', verbose_name='\u5bb9\u5668YML\u5206\u7ec4'),
        ),
        migrations.AddField(
            model_name='dockercompose',
            name='dockerhost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.DockerHost', verbose_name='\u5bb9\u5668\u5bbf\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='dockercompose',
            name='yml',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.DockerYml', verbose_name='\u5bb9\u5668YML'),
        ),
        migrations.AddField(
            model_name='cmd_log',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='cmd',
            name='host',
            field=models.ManyToManyField(blank=True, to='cmdb.Host', verbose_name='\u6267\u884c\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='cmd',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba'),
        ),
        migrations.AddField(
            model_name='balance2host',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u540e\u7aef\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='balance',
            name='group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.HostGroup', verbose_name='\u7ec4/\u5b89\u5168\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='balance',
            name='host',
            field=models.ManyToManyField(db_table='cmdb_balance_host', to='cmdb.Host', verbose_name='\u540e\u7aef\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ManyToManyField(blank=True, help_text='\u54ea\u4e9b\u767b\u9646\u7528\u6237\u80fd\u5bf9\u5f53\u524d\u9879\u8fdb\u884c\u64cd\u4f5c\uff0c\u8d85\u7ea7\u7528\u6237\u9ed8\u8ba4\u6709\u64cd\u4f5c\u6743\u9650', to=settings.AUTH_USER_MODEL, verbose_name='\u7f51\u7ad9\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='appfiles',
            name='cmd',
            field=models.ForeignKey(help_text='\u4e3b\u673a\u6700\u8fd1\u4e00\u6b21\u6267\u884c\u7684\u547d\u4ee4(\u6536\u96c6tomcat\u6587\u4ef6\u72b6\u6001)', on_delete=django.db.models.deletion.CASCADE, to='cmdb.CMD', verbose_name='\u547d\u4ee4'),
        ),
        migrations.AddField(
            model_name='appfiles',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='app_log',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Host', verbose_name='\u4e3b\u673a'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([('app', 'host')]),
        ),
        migrations.AlterUniqueTogether(
            name='es',
            unique_together=set([('host', 'port')]),
        ),
        migrations.AlterUniqueTogether(
            name='dockeryml',
            unique_together=set([('group', 'file')]),
        ),
        migrations.AlterUniqueTogether(
            name='dockerimagefile',
            unique_together=set([('name', 'ver', 'dockerhost')]),
        ),
        migrations.AlterUniqueTogether(
            name='dockercompose',
            unique_together=set([('yml', 'dockerhost')]),
        ),
        migrations.AlterUniqueTogether(
            name='balance2host',
            unique_together=set([('balance', 'host')]),
        ),
    ]
